### ISSUE TITLE
Table of Contents error

### ISSUE THREAD

**Issue by sambuaneesh** [karthikv1392/cs3301_osn_2024#8]
## Problem
No matter which entry we choose, the Table of Contents always opens to the most recent entry, as can be seen in the visualization below.
We are unable to open the Lecture 1 pdf, as can be seen in the GiF below.

## Visualization
![bug](https://github.com/karthikv1392/cs3301_osn/assets/75294086/aded3017-1c64-4e43-b606-26f0b4049373)

**Comment by karthikv1392** [comment]
This has been solved
